### ISSUE TITLE
Following directions to run todo example results in an install exception

### ISSUE THREAD

**Issue by ericallam** [facebook/relay#906]
Following these steps:

```bash
git clone https://github.com/facebook/relay.git
cd relay/examples/todo && npm install
npm start
```

Results in an exception while running `npm install`:

```
> babel-relay-plugin@0.7.1 prepublish /Users/eric/code/TinyMatter/Survivor/learning/relay/scripts/babel-relay-plugin
> npm run build


> babel-relay-plugin@0.7.1 build /Users/eric/code/TinyMatter/Survivor/learning/relay/scripts/babel-relay-plugin
> node scripts/build-lib

module.js:329
    throw err;
    ^

Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/eric/code/TinyMatter/Survivor/learning/relay/scripts/babel-relay-plugin/scripts/build-lib:3:15)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/eric/.nvm/versions/node/v5.2.0/bin/node" "/Users/eric/.nvm/versions/node/v5.2.0/bin/npm" "run" "build"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! babel-relay-plugin@0.7.1 build: `node scripts/build-lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-relay-plugin@0.7.1 build script 'node scripts/build-lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build-lib
npm ERR! You can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eric/code/TinyMatter/Survivor/learning/relay/scripts/babel-relay-plugin/npm-debug.log
npm ERR! addLocal Could not install /Users/eric/code/TinyMatter/Survivor/learning/relay/scripts/babel-relay-plugin

> react-relay@0.7.1 prepublish /Users/eric/code/TinyMatter/Survivor/learning/relay
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && npm run build

module.js:329
    throw err;
    ^

Error: Cannot find module '/Users/eric/code/TinyMatter/Survivor/learning/relay/node_modules/fbjs-scripts/node/check-dev-engines.js'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
npm ERR! addLocal Could not install /Users/eric/code/TinyMatter/Survivor/learning/relay
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/eric/.nvm/versions/node/v5.2.0/bin/node" "/Users/eric/.nvm/versions/node/v5.2.0/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! babel-relay-plugin@0.7.1 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-relay-plugin@0.7.1 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-relay-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls babel-relay-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eric/code/TinyMatter/Survivor/learning/relay/examples/todo/npm-debug.log
```

Running `npm install` in the root of the *relay* directory before `npm install`ing the todo example fixes this exception.

Running on node v5.2.0 and npm 3.3.12

**Comment by nicerr** [comment]
Have you looked here: [https://github.com/facebook/relay/issues/850#issuecomment-191361083] 
namely:
I also had this problem until I found out the example has two global modules as prerequisites. This is not described in the current README.md: 
npm install -g babel-core
npm install -g babel-cli

I see there is a Pull Request to rectify this [#798](https://github.com/facebook/relay/pull/798), but it's been sitting there for 27 days now.

**Comment by akeating** [comment]
It looks like a race to me. `babel-relay-plugin@0.7.3 prepublish` is being called before `todo preinstall`

**Comment by mgleason** [comment]
Looks like the README in the todo example folder is incorrect.  I suspect you can globally install babel-core ad babel-CLI as @nicerr suggests.  I guessed the README author downloaded/cloned and npm installed https://github.com/facebook/relay first - then cd'd to the examples directory and npm install'ed there.
NOTE: this assumes the "relay-master" folder is where you downloaded/cloned https://github.com/facebook/relay. 

Here's what I had to do to get it running.   You'll need to edit the path if you put it somewhere else.

1. cd ~/relay-master; npm install
2. cd ~/relay-master/scripts/babel-relay-plugin; npm install
3. cd ~/relay-master/examples/todo; npm install
4. npm start

Additional info:
The README in the "todo" example say:  "## Installation ``` npm install ``` ## Running Start a local server: ``` npm start".  Unfortunately, that results in:

> Error: Cannot find module 'babel-core'.

To get the running I needed to:

1. cd ~/relay-master; npm install

After this tried "cd ~/relay-master/examples/todo; npm install", but got:

> babelAdapter.js: Unknown option: relay-master/scripts/babel-relay-plugin/.babelrc.presets

Next:

2. cd ~/relay-master/scripts/babel-relay-plugin; npm install

Finally 

3. cd ~/relay-master/examples/todo; npm install
4. npm start

**Comment by kevinSuttle** [comment]
Good lord. You have to do this with every example.

**Comment by edvinerikson** [comment]
`npm i --ignore-scripts` seems to work on NPM 3.3.6

**Comment by steveluscher** [comment]
I cleaned up the examples for the release of [0.9.0](https://github.com/facebook/relay/releases/tag/v0.9.0). Give them a try!

I tried (on OS X):

```
# Delete every globally installed npm module
npm ls -gp --depth=0 | awk -F/ '/node_modules/ && !/\/npm$/ {print $NF}' | xargs npm -g rm
# Return to pristine, first-cloned state
git clean -dfx
# Install and run the todo example
cd examples/todo
npm install
npm start
```

…and had success. [Here was the output](https://gist.github.com/steveluscher/ac88aaaa340c6f92c6cca611ec31e2c0). This was with npm v2.14.12 and Node v4.2.6.

If you experience trouble that I didn't, please do open an issue with your npm/Node versions and your output. Thanks for helping to keep the examples healthy everyone!

**Comment by steveluscher** [comment]
We're in the middle of a little bit of a revert/unrevert situation, so if anyone wants to try the examples in the next 24 hours or so be sure to check out the v0.9.0 tag:

```
git clone git@github.com:facebook/relay.git
cd relay
git checkout tags/v0.9.0
```
