### ISSUE TITLE
Cannot find module "./filterObject" in relay 0.3.0

### ISSUE THREAD

**Issue by mhart** [facebook/relay#301]
I'm getting:
```
Uncaught Error: Cannot find module "./filterObject"
webpackMissingModule @ relay.js:5306
(anonymous function) @ relay.js:5306
__webpack_require__@ relay.js:33
(anonymous function)@ relay.js:11364
__webpack_require__@ relay.js:33
(anonymous function)@ relay.js:13790
(anonymous function)@ relay.js:13828
__webpack_require__@ relay.js:33
(anonymous function)@ relay.js:101
__webpack_require__@ relay.js:33
(anonymous function)@ relay.js:53
(anonymous function)@ relay.js:56
webpackUniversalModuleDefinition@ relay.js:12
(anonymous function)@ relay.js:13
```
When trying to use `dist/relay.js` (or `dist/relay.min.js`) just included in a script tag on the page:

```html
<script src=//fb.me/react-0.14.0-rc1.min.js></script>
<script src=//fb.me/react-dom-0.14.0-rc1.min.js></script>
<script src=/relay/relay.js></script>
```
(`/relay` is serving statically from `node_modules/react-relay/dist`)

This does not occur in 0.2.1

**Comment by mhart** [comment]
FWIW I also have a browserified bundle.js included as a script tag further down – it does not include any of React or Relay in the bundle though, only my components. React and Relay are referenced in the following manner:
```js
var Relay = (typeof window !== "undefined" ? window['Relay'] : typeof global !== "undefined" ? global['Relay'] : null);
```
Again, this worked fine in 0.2.1

**Comment by mhart** [comment]
Actually, scratch that, the error occurs even if I comment out the browserified bundle, so we can remove that from the equation.

Literally these three lines can reproduce the error:
```html
<script src=//fb.me/react-0.14.0-rc1.min.js></script>
<script src=//fb.me/react-dom-0.14.0-rc1.min.js></script>
<script src=/relay/relay.js></script>
```

**Comment by wincent** [comment]
Thanks for the heads up. You need a later version of fbjs to get `filterObject` (see https://github.com/facebook/relay/commit/3f39600969b90294eeffd7a8bd3c1a2586fef387). Not at a computer now, but that hunk looks like it somehow got reverted. I'll push a fix presently.

**Comment by wincent** [comment]
> but that hunk looks like it somehow got reverted

Er, actually, no. I just suck at reading diffs on my phone, the dependency is still intact in the `package.json`.

Can you check for me whether you still see this error after an `npm update`?

**Comment by zpao** [comment]
The problem described above is actually with the dist file, not the other parts of the node module. I can reproduce this easily just by loading the dist file as mentioned. And actually, it just looks like v0.3 was built & packaged without updating fbjs locally (which would explain why it's looking at `./filterObject`, it didn't have an updated module map from fbjs). `lib/buildRQL` also isn't pointing into fbjs for filterObject.

You should rebuild and publish 0.3.1 asap.

**Comment by wincent** [comment]
> You should rebuild and publish 0.3.1 asap.

Doing that right now.

**Comment by zpao** [comment]
:thumbsup: Thanks Greg!

**Comment by mhart** [comment]
Confirmed, thanks all.
