### ISSUE TITLE
[Modern] TypeError: this._network.execute is not a function

### ISSUE THREAD

**Issue by mmjd** [facebook/relay#2151]
after upgrading relay group of modules from 1.2.0-rc.1 to 1.4.1, I get the following error when use babel-node to run my server.js. 

```
TypeError: this._network.execute is not a function
```
this line is in relay-runtime.js

**Comment by sibelius** [comment]
_network is a private api, it could change anytime

**Comment by mmjd** [comment]
my fault. I had copied RelayNetwork source to catch onError. how is it possible to listen for network errors in new API?

**Comment by sibelius** [comment]
on modern just use fetchQuery

**Comment by mmjd** [comment]
thank you
