### ISSUE TITLE
Duplicate directive definition 'connection'.

### ISSUE THREAD

**Issue by gv04is402** [facebook/relay#3781]
# issues
Compilation failed. after upgrade relay to v13.x

**Comment by alunyov** [comment]
Hello, there is probably something incorrect with your setup. You maybe have multiple schema files that define `@connection` directive.

If you have a repro, please share a link.

**Comment by gv04is402** [comment]
Thanks,
Schema file is generated from "get-graphql-schema" please find the repo link below

https://github.com/gv04is402/relay_example

**Comment by alunyov** [comment]
Thanks @gv04is402 

It looks like your GraphQL server also defines directive `@connection` here: https://github.com/gv04is402/relay_example/blob/9e6e10a8e7d7c7a3820dfb06a00f8b9db1d04166/src/schema/app_schema.graphql#L1

Conflict is happening because Relay compiler, also defines `@connection` as a client-only extension directive. We probably didn't correctly handle/validate these cases in JS version.

Is it possible to change/rename the server directive `@connection` in your app?
