### ISSUE TITLE
After update to 1.5 throwing TypeError: getOperation is not function

### ISSUE THREAD

**Issue by Nodonisko** [facebook/relay#2369]
After update to relay-runtime and relay-compiler to 1.5.0, I regenerated all generated files, then run app, but it throws runtime type error. Also tried to delete _generated_ folders and then run complier again, but same result.

Error:

> Unhandled JS Exception: TypeError: getOperation is not a function
> 
> This error is located at:
>     in ReactRelayQueryRenderer (at RecommendationScreen.js:73)
>     in RecommendationScreen (at withScreen.js:117)
>     in _class (at Navigation.js:83)
>     in Provider (at Root.js:19)
>     in ThemeProvider (at Root.js:18)
>     in Provider (at Root.js:17)
>     in Root (at Navigation.js:82)
>     in _class2 (at renderApplication.js:35)
>     in RCTView (at View.js:71)
>     in View (at AppContainer.js:102)
>     in RCTView (at View.js:71)
>     in View (at AppContainer.js:122)
>     in AppContainer (at renderApplication.js:34)

This is my query:
```      
     <QueryRenderer
        environment={environment}
        variables={{ first: 28 }}
        query={graphql`
          query RecommendationScreenQuery($first: Int) {
            recommendations(first: $first) {
              edges {
                node {
                  id
                  headline
                  tagline
                  product {
                    category {
                      id
                    }
                  }
                }
              }
            }
          }
        `}
        render={this.renderScreen}
      />
```

With previous version 1.4 everything works.  I haven't schema in src folder.

Versions:

    "react": "16.2.0"
    "react-native": "0.52.0"
    "relay-devtools": "^1.4.0"
    "relay-local-schema": "^0.6.2"
    "relay-runtime": "^1.5.0"
    "relay-compiler": "^1.5.0"

**Comment by sibelius** [comment]
maybe missing @connection

**Comment by Nodonisko** [comment]
@sibelius I think connection is required only in pagination container

**Comment by zth** [comment]
Are you using the standard QueryRenderer from react-relay, and not another one like https://github.com/relay-tools/relay-query-lookup-renderer?

**Comment by Nodonisko** [comment]
@zth Everything is standart.

**Comment by sibelius** [comment]
@Nodonisko can u share this queryrenderer component?

**Comment by edvinerikson** [comment]
Maybe you forgot to update `react-relay`?

**Comment by Nodonisko** [comment]
@edvinerikson Sounds promising, I probablby updated only this `relay-*` will try it.

**Comment by Nodonisko** [comment]
Closing it was caused by using old `react-relay` + then appear next problem related to `relay-local-schema`

More info: https://github.com/facebook/relay/issues/2369
